### ISSUE TITLE
Issue when doing Dungeon

### ISSUE THREAD

**Issue by Omtrw** [fnk93/Summoners-War-Bot#11]
File "mycode_hive.py", line 21, in <module>
    a.doDungeon(9001,10,200)
  File "D:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1501, in doDungeon
    if dungeon_id not in [dungeon['dungeon_id'] for dungeon in self.dungeon_list]:
TypeError: 'NoneType' object is not iterable

**Comment by fnk93** [comment]
Ok, since you're using mycode_hive.py I added all the requests which will be sent when starting the game to the file.

Your issue should be solved by this, as I included a lot of data handling into the api.py to protect you from completing things you shouldn't be able to complete :D But I forgot to add those lines to the mycode_hive.py
